### ISSUE TITLE
Blog posts appear to be broken.

### ISSUE THREAD

**Issue by lionirdeadman** [NickvisionApps/nickvisionapps.github.io#15]
This article appears to have a page (https://nickvision.org/posts/0123/addressingMemoryIssuesInDenaro.html) and contents (https://github.com/NickvisionApps/nickvisionapps.github.io/blob/ac9bbe16ebb861cca211b15626b2ae63f20bb9f9/_posts/2023-01-16-addressing-memory-issues-in-denaro.md) but it is not displayed on the page.

**Comment by nlogozzo** [comment]
That's because that article was written for our old site, which was in markdown and the new site that we have now is html. I never converted the article properly to HTML, plus it's kind of old, so I just left it like that.

If and when I write new blog posts, they will be in proper HTML and displayed correctly on the site.
